import { HardwarePreset } from '@/types/hardware';

export const HARDWARE_PRESETS: HardwarePreset[] = [
  {
    id: 'preset_budget_laptop',
    name: '8 GB RAM / Integrated GPU',
    description: 'Entry laptop or office desktop without discrete GPU',
    specs: {
      gpuName: 'Intel Iris Xe / AMD Radeon Vega',
      vramGB: 0,
      ramGB: 8,
      cpuName: 'Intel Core i5-1135G7 / Ryzen 5 5500U',
      cpuCores: 8,
      storageGB: 512,
      availableDiskGB: 45,
      os: 'windows',
      useCase: 'general',
      targetContext: 4096,
      isUnifiedMemory: false,
    },
  },
  {
    id: 'preset_mainstream_16gb_6gb',
    name: '16 GB RAM / 6 GB VRAM',
    description: 'Mainstream gaming laptop with GTX 1660 / RTX 3060 6GB',
    specs: {
      gpuName: 'NVIDIA GeForce RTX 3060 Laptop (6GB)',
      vramGB: 6,
      ramGB: 16,
      cpuName: 'AMD Ryzen 7 5800H',
      cpuCores: 8,
      storageGB: 1000,
      availableDiskGB: 120,
      os: 'windows',
      useCase: 'coding',
      targetContext: 8192,
      isUnifiedMemory: false,
    },
  },
  {
    id: 'preset_popular_32gb_8gb',
    name: '32 GB RAM / 8 GB VRAM (RTX 4060 / 5050)',
    description: 'Sweet spot gaming desktop / laptop with 8GB VRAM',
    specs: {
      gpuName: 'NVIDIA GeForce RTX 4060 / 5050',
      vramGB: 8,
      ramGB: 32,
      cpuName: 'Intel Core i5-13500HX',
      cpuCores: 14,
      storageGB: 2000,
      availableDiskGB: 280,
      os: 'windows',
      useCase: 'coding',
      targetContext: 8192,
      isUnifiedMemory: false,
    },
  },
  {
    id: 'preset_creator_32gb_12gb',
    name: '32 GB RAM / 12 GB VRAM (RTX 4070)',
    description: 'High-performance creator desktop for 14B models',
    specs: {
      gpuName: 'NVIDIA GeForce RTX 4070 (12GB)',
      vramGB: 12,
      ramGB: 32,
      cpuName: 'AMD Ryzen 7 7800X3D',
      cpuCores: 8,
      storageGB: 2000,
      availableDiskGB: 450,
      os: 'windows',
      useCase: 'reasoning',
      targetContext: 16384,
      isUnifiedMemory: false,
    },
  },
  {
    id: 'preset_enthusiast_64gb_16gb',
    name: '64 GB RAM / 16 GB VRAM (RTX 4080)',
    description: 'High-end developer workstation for fast 14B-32B inference',
    specs: {
      gpuName: 'NVIDIA GeForce RTX 4080 (16GB)',
      vramGB: 16,
      ramGB: 64,
      cpuName: 'Intel Core i7-14700K',
      cpuCores: 20,
      storageGB: 4000,
      availableDiskGB: 800,
      os: 'linux',
      useCase: 'coding',
      targetContext: 32768,
      isUnifiedMemory: false,
    },
  },
  {
    id: 'preset_flagship_64gb_24gb',
    name: '64 GB RAM / 24 GB VRAM (RTX 3090 / 4090)',
    description: 'Workstation for full 32B GPU acceleration & 70B offload',
    specs: {
      gpuName: 'NVIDIA GeForce RTX 4090 (24GB)',
      vramGB: 24,
      ramGB: 64,
      cpuName: 'AMD Ryzen 9 7950X',
      cpuCores: 16,
      storageGB: 4000,
      availableDiskGB: 1200,
      os: 'linux',
      useCase: 'reasoning',
      targetContext: 32768,
      isUnifiedMemory: false,
    },
  },
  {
    id: 'preset_mac_m_18gb',
    name: 'Apple Silicon 18-24 GB Unified (M3/M4 Pro)',
    description: 'MacBook Pro with unified memory architecture',
    specs: {
      gpuName: 'Apple M3 Pro (14-core GPU)',
      vramGB: 18,
      ramGB: 18,
      cpuName: 'Apple M3 Pro (11-core CPU)',
      cpuCores: 11,
      storageGB: 512,
      availableDiskGB: 180,
      os: 'macos',
      useCase: 'general',
      targetContext: 16384,
      isUnifiedMemory: true,
    },
  },
  {
    id: 'preset_mac_max_64gb',
    name: 'Apple Silicon 64-128 GB Unified (M3/M4 Max)',
    description: 'Mac Studio / MacBook Pro Max capable of running 70B models',
    specs: {
      gpuName: 'Apple M3 Max (30-core GPU)',
      vramGB: 64,
      ramGB: 64,
      cpuName: 'Apple M3 Max (14-core CPU)',
      cpuCores: 14,
      storageGB: 1000,
      availableDiskGB: 450,
      os: 'macos',
      useCase: 'research',
      targetContext: 32768,
      isUnifiedMemory: true,
    },
  },
];
